[syntax]
    level = "LuaJIT3"

[layout]
    max_line_width     = 196
    table_expand       = "Auto"
    call_args_expand   = "Never"
    func_params_expand = "Never"

[output]
    trailing_table_separator = "Multiline"
    single_arg_call_parens   = "Always"

[comments]
    align_in_statements = true

[spacing]
    space_before_lambda_func_paren = false

[align]
    continuous_assign_statement = true
    table_field                 = true
