array_width                         = 196
attr_fn_like_width                  = 196
binop_separator                     = "Front"
brace_style                         = "SameLineWhere"
chain_width                         = 128
color                               = "Auto"
combine_control_expr                = true
comment_width                       = 128
control_brace_style                 = "AlwaysSameLine"
doc_comment_code_block_width        = 196
edition                             = "2024"
empty_item_single_line              = true
fn_call_width                       = 128
fn_params_layout                    = "Tall"
fn_single_line                      = true
force_explicit_abi                  = true
format_generated_files              = true
format_macro_bodies                 = true
format_macro_matchers               = true
format_strings                      = true
group_imports                       = "Preserve"
hex_literal_case                    = "Upper"
ignore                              = []
imports_granularity                 = "Preserve"
imports_indent                      = "Block"
imports_layout                      = "Mixed"
indent_style                        = "Block"
inline_attribute_width              = 0
match_arm_blocks                    = true
match_arm_leading_pipes             = "Never"
max_width                           = 256
merge_derives                       = true
newline_style                       = "Auto"
remove_nested_parens                = true
reorder_impl_items                  = true
reorder_imports                     = true
reorder_modules                     = true
required_version                    = "1.8.0"
short_array_element_width_threshold = 10
single_line_if_else_max_width       = 128
single_line_let_else_max_width      = 128
space_after_colon                   = true
struct_field_align_threshold        = 256
struct_lit_width                    = 196
struct_variant_width                = 196
style_edition                       = "2024"
tab_spaces                          = 4
trailing_comma                      = "Vertical"
trailing_semicolon                  = true
type_punctuation_density            = "Wide"
use_small_heuristics                = "Default"
