local utils   = require("lua.util")
local lazygit = require("lazygit")
lazygit.setup()

utils.mapGeneral("lg", lazygit.toggle)
utils.mapGeneral("<leader>fg", Snacks.picker.grep, { desc = "Grep" })
utils.mapGeneral("<leader>cs", Snacks.picker.colorschemes, { desc = "Choosing colorschemes" })
utils.mapGeneral("<C-s>", "<cmd>w<CR>")
utils.mapGeneral("<C-c>", "<cmd>%y+<CR>")
utils.mapGeneral("d<leader>", "<cmd>%d+<CR>")
utils.mapGeneral("tt", function() Snacks.terminal.toggle({ "nu" }) end)
utils.mapGeneral("<leader>rn", function()
    utils.propmptInput({ expand = true, prompt = "", icon_hl = "SnacksInputIcon" }, function(input) vim.lsp.buf.rename(input) end)
end)

vim.keymap.set("n", "<leader>ca", function() require("tiny-code-action").code_action({}) end, { noremap = true, silent = true })
vim.keymap.set("n", "<C-k>", vim.lsp.buf.hover)
vim.keymap.set("n", "<C-f>", MiniFiles.open)
vim.keymap.set("n", "ff", function()
    _G.LOAD_FFF()
    require("fff").find_files({ grep = { modes = { "fuzzy", "regex", "plain" } } })
end, { desc = "FFFind files" }
)
vim.keymap.set("n", "fg", function()
    _G.LOAD_FFF()
    require("fff").live_grep({ grep = { modes = { "fuzzy", "regex", "plain" } } })
end, { desc = "FFFLivegrep" }
)
